[package]
name = "auto-add-route"
version = "0.1.0"
edition = "2021"

[dependencies]
pcap = "0.9.1"
etherparse = "0.10.1"
trust-dns-proto = "0.21.1"
log = "0.4.14"
env_logger = "0.9.0"
clap = { version = "3.1.6", features = ["derive"] }